# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
     npm install
     npm run cy:grepTags
   displayName: "npm install and Run Cypress test"
   env:
     # map the secret Cypress record key as environmental variable for this step
     CYPRESS_RECORD_KEY: $(CYPRESS_RECORD_KEY)

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'